[package]
name = "OmniAgent"
version = "0.1.0"
edition = "2021"
authors = ["Tristan J. Poland"]
description = "Cross-platform Docker management agent with automatic initialization"
license = "MIT"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
console = "0.15"
reqwest = { version = "0.11", features = ["json"] }
sysinfo = "0.33.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.50"
winapi = { version = "0.3", features = ["winerror", "handleapi", "fileapi", "namedpipeapi", "winbase"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.26", features = ["process"] }

[[bin]]
name = "omniagent"
path = "src/main.rs"